# MongoDB authentication elements

mongo_username = "pdemaers"
mongo_password= "nKZmkEt4BI5PGolE"
mongo_cluster_url = "cluster0.lzhjxqo.mongodb.net"
DATABASE_NAME = "personal"
COLLECTION_NAME = "utilities"