# Everythin in this section will be available as an environment variable

# Database connection
MONGODB_URL = 'mongodb+srv://pdemaers:nKZmkEt4BI5PGolE@cluster0.lzhjxqo.mongodb.net/'
DATABASE_NAME = 'personal'
COLLECTION_NAME = 'utilities'


# User management